//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CmdPalVsCode.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CmdPalVsCode.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string item_details_path {
            get {
                return ResourceManager.GetString("item_details_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        internal static string item_details_target {
            get {
                return ResourceManager.GetString("item_details_target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string item_details_type {
            get {
                return ResourceManager.GetString("item_details_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No recent folders or workspaces found.
        /// </summary>
        internal static string no_items_found {
            get {
                return ResourceManager.GetString("no_items_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try opening a folder or workspace to see recent items here..
        /// </summary>
        internal static string no_items_found_subtitle {
            get {
                return ResourceManager.GetString("no_items_found_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Recent.
        /// </summary>
        internal static string page_command_name {
            get {
                return ResourceManager.GetString("page_command_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Studio Code.
        /// </summary>
        internal static string page_title {
            get {
                return ResourceManager.GetString("page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What should happen after opening a VS Code workspace.
        /// </summary>
        internal static string setting_commandResult_desc {
            get {
                return ResourceManager.GetString("setting_commandResult_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Result Action.
        /// </summary>
        internal static string setting_commandResult_label {
            get {
                return ResourceManager.GetString("setting_commandResult_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss.
        /// </summary>
        internal static string setting_commandResult_option_dismiss_label {
            get {
                return ResourceManager.GetString("setting_commandResult_option_dismiss_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back.
        /// </summary>
        internal static string setting_commandResult_option_goback_label {
            get {
                return ResourceManager.GetString("setting_commandResult_option_goback_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep Open.
        /// </summary>
        internal static string setting_commandResult_option_keepopen_label {
            get {
                return ResourceManager.GetString("setting_commandResult_option_keepopen_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This setting determines which edition is used when a folder or workspace has been opened in both the default and Insider editions of VS Code.
        /// </summary>
        internal static string setting_preferredEdition_desc {
            get {
                return ResourceManager.GetString("setting_preferredEdition_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred Edition.
        /// </summary>
        internal static string setting_preferredEdition_label {
            get {
                return ResourceManager.GetString("setting_preferredEdition_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string setting_preferredEdition_option_default_label {
            get {
                return ResourceManager.GetString("setting_preferredEdition_option_default_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insider.
        /// </summary>
        internal static string setting_preferredEdition_option_insider_label {
            get {
                return ResourceManager.GetString("setting_preferredEdition_option_insider_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displayed tags.
        /// </summary>
        internal static string setting_tagType_desc {
            get {
                return ResourceManager.GetString("setting_tagType_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        internal static string setting_tagType_label {
            get {
                return ResourceManager.GetString("setting_tagType_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string setting_tagType_option_none_label {
            get {
                return ResourceManager.GetString("setting_tagType_option_none_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        internal static string setting_tagType_option_target_label {
            get {
                return ResourceManager.GetString("setting_tagType_option_target_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string setting_tagType_option_type_label {
            get {
                return ResourceManager.GetString("setting_tagType_option_type_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &amp; Target.
        /// </summary>
        internal static string setting_tagType_option_typeandtarget_label {
            get {
                return ResourceManager.GetString("setting_tagType_option_typeandtarget_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details panel.
        /// </summary>
        internal static string settings_showDetails_desc {
            get {
                return ResourceManager.GetString("settings_showDetails_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show details panel.
        /// </summary>
        internal static string settings_showDetails_label {
            get {
                return ResourceManager.GetString("settings_showDetails_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strict Search.
        /// </summary>
        internal static string settings_useStrictSearch_desc {
            get {
                return ResourceManager.GetString("settings_useStrictSearch_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use strict search.
        /// </summary>
        internal static string settings_useStrictSearch_label {
            get {
                return ResourceManager.GetString("settings_useStrictSearch_label", resourceCulture);
            }
        }
    }
}
